<a href="https://colab.research.google.com/github/FarhanFansuri/scikit-learn/blob/main/TA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Import Libraries

In [3]:
import numpy as np
import pandas as pd
import sklearn
from sklearn.cluster import KMeans
from sklearn.preprocessing import scale
import sklearn.metrics as sm
from sklearn.metrics import confusion_matrix, classification_report

In [4]:
dataset_jml_TL = pd.read_excel('/content/Indo_27_16166752.xls')

In [5]:
dataset_jml_TL

,"Jumlah Desa/Kelurahan yang Mengalami Bencana Alam Tanah Longsor Menurut Kabupaten/Kota di Provinsi Jawa Timur, 2019-2021",Unnamed: 1,Unnamed: 2,Unnamed: 3
0,Kabupaten/Kota\nRegency/Municipality,Tanah Longsor/Landslide,NaN,NaN
1,NaN,2019,2020,2021
2,Kabupaten/Regency,NaN,NaN,NaN
3,Pacitan,54,23,64
4,Ponorogo,19,12,16
5,Trenggalek,31,27,33
6,Tulungagung,10,11,12
7,Blitar,11,8,19
8,Kediri,4,8,10
9,Malang,17,20,44
10,Lumajang,9,7,10
11,Jember,18,9,23
12,Banyuwangi,4,2,3
13,Bondowoso,9,3,5
14,Situbondo,6,2,7
15,Probolinggo,8,12,9
16,Pasuruan,13,13,19
17,Sidoarjo,-,-,-
18,Mojokerto,3,3,7
19,Jombang,3,3,7
20,Nganjuk,2,7,7
21,Madiun,6,7,9
22,Magetan,7,20,15
23,Ngawi,2,1,1
24,Bojonegoro,28,23,18
25,Tuban,6,4,4
26,Lamongan,3,6,4
27,Gresik,-,3,3
28,Bangkalan,7,4,9
29,Sampang,6,5,9
30,Pamekasan,9,13,15
31,Sumenep,3,6,6
32,Kota/Municipality,NaN,NaN,NaN
33,Kediri,-,1,-
34,Blitar,2,5,1
35,Malang,8,12,19
36,Probolinggo,-,-,-
37,Pasuruan,-,-,-
38,Mojokerto,-,-,-
39,Madiun,-,-,-
40,Surabaya,-,-,-
41,Batu,1,2,6
42,Jawa Timur,309,282,414
43,Catatan/Note : Kejadian dalam setahun sebelum...,NaN,NaN,NaN